De-sync of ports in older versions of BISDN linux
bisdn/bisdn.github.io pull request #103
Opened 2021-06-30 14:02 UTC by hilmarm

* Added mention of the port state sync issue due to OF-DPA on bootup

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

2021-06-30 14:03 UTC, hilmarm commented on limitations.md
> +their current state, and only then registers notifications about port state
I am not entirely happy with this: "initializes ports with their current state", what exactly does current state mean here @KanjiMonster

2021-06-30 14:34 UTC, hilmarm commented on limitations.md
> +their current state, and only then registers notifications about port state
Or can we be more precise in what we mean.

2021-07-01 04:04 UTC, ideaship requested changes

2021-07-01 08:48 UTC, hilmarm commented on limitations.md
> +their current state, and only then registers notifications about port state
Now mentions the linkscan handler, which is responsible for the port state updates in OF-DPA

2021-07-01 08:51 UTC, hilmarm commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
added

2021-07-01 08:51 UTC, hilmarm commented on limitations.md
> +
fixed

2021-07-01 08:59 UTC, KanjiMonster commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
This has nothing to do with systemd-networkd - this is purely about the physical state, i.e. if a cable is plugged in and has a link. The issue then can happen regardless if the port is administratively up or do.

2021-07-01 09:20 UTC, ideaship commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
systemd-networkd is simply an example of how "network configuration is applied during or shortly after, booting up", as opposed to logging in some time later and configuring the network manually, e.g. using ip(8). So if the issue has nothing to do with systemd-networkd, then "if network configuration is applied during, or shortly after, booting up" is also wrong.

2021-07-01 09:57 UTC, KanjiMonster commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
Right, this part is also wrong.

The issue happens if ports are physically connected, and the link gets established during that window. Then the link up event will be missed, and the internal cached link state will remain in the wrong state (until the port is brought down and up again). This all happens before OF-DPA/ofagent even accepts connections, so before any port interfaces exist in linux.

2021-07-01 11:15 UTC, hilmarm commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
So the 'link up event' here has nothing to do with configuring links/ports using sytemd or iproute2. How should we reword it so that it is correct?

"If changes in port state during this time?"
I really can't think of how to word this properly.

2021-07-02 09:16 UTC, hilmarm commented on limitations.md
> +or shortly after, booting up, e.g. using systemd-networkd.
Reworded quite a bit, can does it look better now @KanjiMonster?

2021-07-05 13:50 UTC, jklare commented on limitations.md
> +## Port state sync issue on boot caused by OF-DPA
What is the result of this? How can a customer identify if he is running into this issue?

2021-07-07 12:51 UTC, hilmarm commented on limitations.md
> +successful registration of the handler will be missed.
```suggestion
successful registration of the handler will be missed.

The port sync issue may be identified by the inability to set a port up, even though there is a physical cable plugged into the port.

E.g having a cable into port2, and running ``ip link set port2 up``, then the output of ``ip link show port2`` should show the state as ``UP``. If the state is ``DOWN``. you likely have a port state sync issue in OF-DPA, which you can resolve by first disabling and then enabling the port again.

``client_drivshell port 2 Enable=false``
``client_drivshell port 2 Enable=true``
```

2021-07-07 12:52 UTC, hilmarm commented on limitations.md
> +## Port state sync issue on boot caused by OF-DPA
Commented suggestion below.

2021-07-07 13:23 UTC, KanjiMonster commented on limitations.md
> +## Port state sync issue on boot caused by OF-DPA
Maybe something along 
```suggestion
## Ports connected during boot may sometimes show as having no carrier in Linux
```
makes it clearer about the visible symptoms (and situation where it happens)

2021-07-08 08:28 UTC, hilmarm commented on limitations.md
> +## Port state sync issue on boot caused by OF-DPA
Updated the description of the problem and how to resolve it

2021-07-08 15:21 UTC, KanjiMonster commented on limitations.md
> +All releases of BISDN Linux prior to version 4.0 suffer from an issue where
```suggestion
All releases of BISDN Linux prior to version 3.7.3 suffer from an issue where
```

2021-07-08 15:21 UTC, KanjiMonster commented on limitations.md
> +the port state might end up out of sync
```suggestion
the port state might end up out of sync.
```

2021-07-13 12:02 UTC, KanjiMonster commented on limitations.md
> +The port sync issue may be identified by the link inability to set a port up
```suggestion
The port sync issue may be identified by the link's inability to set a port up
```

2021-07-13 13:56 UTC, KanjiMonster commented
Please sign off your commits so DCO is happy.

2021-07-13 14:22 UTC, merged