dhcp multicast
bisdn/bisdn.github.io pull request #111
Opened 2021-07-27 08:26 UTC by hilmarm

2021-07-27 09:38 UTC, rubensfig approved these changes

2021-07-27 13:56 UTC, hilmarm commented
Changed 'time to appear' from several days, to basically any time window.

2021-07-28 10:32 UTC, KanjiMonster requested changes

2021-07-28 10:32 UTC, KanjiMonster commented on limitations.md
> +setting ''FLAGS_multicast=false'' in the [baseboxd configuration file](../getting_started/configure_baseboxd.html#setup-baseboxd).
> There is a bug

Unnecessary fluff. It is obvious this is a bug.

> that causes DHCP packets to not get forwarded properly, and this
issue may appear in as little as a few minutes or take several days of switch
uptime.

I don't think the time frame is really relevant or intersting here, and can just be dropped. Also this somewhat implies that uptime is part of what triggers it, but it isn't.

Just say something like "The switch may sometimes stop forwarding DHCP packets correctly."

> The only known permanent fix

This is not a fix, it is a workaround, as it breaks other functionality (multicast support).

Also it might be worth to note that this workaround only exists in 4.0.

> to disable multicast by
setting ''FLAGS_multicast=false'' in the [baseboxd configuration file](../getting_started/configure_baseboxd.html#setup-baseboxd).

Maybe just link to the section you add below where you describe how to do that?

2021-07-28 10:32 UTC, KanjiMonster commented on limitations.md
> +Rebooting the switch will only temporarily resolve the issue.
I think this sentence in unneeded, and only needed of reboot doesn't help (i.e. if a power cycle is required).

2021-07-28 11:09 UTC, hilmarm commented on limitations.md
> +setting ''FLAGS_multicast=false'' in the [baseboxd configuration file](../getting_started/configure_baseboxd.html#setup-baseboxd).
Updated comments.
THe last point I am not entirely sure about which link you mean, both the IGMP/MULTICAST page, and the limitations page point to the page where the configuration file is shown, and both have the same sentence, i.e., 'add this flag to the config file'

2021-07-28 11:10 UTC, hilmarm commented on limitations.md
> +Rebooting the switch will only temporarily resolve the issue.
sentence removed

2021-07-28 12:39 UTC, KanjiMonster commented on limitations.md
> +setting ''FLAGS_multicast=false'' in the [baseboxd configuration file](../getting_started/configure_baseboxd.html#setup-baseboxd).
What I mean is instead of copypasting how to toggle multicast support, link to network_configuration/igmpmldsnooping.md#enablingdisabling-multicast where we already describe it. And if we ever need to update the description, we only need to do that at one place.

2021-07-29 08:16 UTC, hilmarm commented on limitations.md
> +setting ''FLAGS_multicast=false'' in the [baseboxd configuration file](../getting_started/configure_baseboxd.html#setup-baseboxd).
Done!

2021-07-29 08:25 UTC, KanjiMonster requested changes

2021-07-29 08:25 UTC, KanjiMonster commented on network_configuration/igmpmldsnooping.md
> +## Enabling/disabling multicast
Maybe call this `Enabling/disabling IGMP/MLD snooping`? Disabling this won't prevent multicast from working, it will just be flooded.

2021-07-29 08:25 UTC, KanjiMonster commented on limitations.md
> +[disable multicast](network_configuration/igmpmldsnooping.md#enablingdisabling-multicast)
```suggestion
[disable multicast](network_configuration/igmpmldsnooping.md#enablingdisabling-multicast).
```

2021-07-29 08:46 UTC, hilmarm commented on network_configuration/igmpmldsnooping.md
> +## Enabling/disabling multicast
Good point. Should I also update the limitations.md section where I refer to 'disable multicast'?

2021-07-29 08:49 UTC, KanjiMonster commented on network_configuration/igmpmldsnooping.md
> +## Enabling/disabling multicast
Yes, that would be good idea

2021-07-29 09:00 UTC, hilmarm commented on network_configuration/igmpmldsnooping.md
> +## Enabling/disabling multicast
Changed section name, and also changed the link in limitations.md to point to the newly named section.
Now says [disable IGMP/MLD snooping] instead of disable multicast.

2021-08-02 12:46 UTC, merged