Celestica Questone 2A known hardware issues
bisdn/bisdn.github.io pull request #112
Opened 2021-07-27 14:15 UTC by hilmarm

LED and fan speed issues mentioned, and also added the Celestica to the list of supported swtiches on the first page (index.html)

2021-07-27 14:25 UTC, KanjiMonster requested changes

2021-07-27 14:25 UTC, KanjiMonster commented on limitations.md
> +
These are two distinct issue, so they should be two different paragraphs.

2021-07-27 14:38 UTC, hilmarm commented on limitations.md
> +
Fixed: separated into two sections.

2021-07-27 15:45 UTC, KanjiMonster requested changes

2021-07-27 15:45 UTC, KanjiMonster commented on limitations.md
> +by having both PSUs connected and powered on.
This is a very bold statement, as there are probably other reasons why the fans might spin at 100%. So I don't think we should claim that this will resolve the issue, but rather suggest that this mght be the issue (e.g. ask to check that both PSUs are connected and have power).

2021-07-28 08:32 UTC, hilmarm commented on limitations.md
> +## Celestica Questone 2A fan issue
updated header

2021-07-28 08:34 UTC, hilmarm commented on limitations.md
> +by having both PSUs connected and powered on.
changed from 'will' to 'might' and a small sentence rewrite.

2021-07-28 08:37 UTC, hilmarm commented on limitations.md
> +## Celestica Questone 2A port LEDs
updated header.

2021-08-04 15:05 UTC, rubensfig approved these changes

2021-08-04 15:06 UTC, merged