static_routing.md: added example with figure
bisdn/bisdn.github.io pull request #117
Opened 2021-09-03 12:31 UTC by hilmarm

Added a simple example taken from our internal switch testing setup

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +10.0.2.0/24 subnet (which is on ``server-2``) via 10.0.3.2
```suggestion
10.0.2.0/24 subnet (which is on ``server-2``) via 10.0.3.2.
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +10.0.1.0/24 subnet (which is on ``sever-1``) via 10.0.3.1
```suggestion
10.0.1.0/24 subnet (which is on ``sever-1``) via 10.0.3.1.
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +10.0.2.0/24 (which is on ``server-2``) via 10.0.1.1
```suggestion
10.0.2.0/24 (which is on ``server-2``) via 10.0.1.1.
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +10.0.1.0/24 (which is on ``server-1``) via 10.0.2.1
```suggestion
10.0.1.0/24 (which is on ``server-1``) via 10.0.2.1.
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +This adds ip address 10.0.2.2/24 to ``eno2`` and a route to the subnet
```suggestion
Add ip address 10.0.2.2/24 to ``eno2`` and a route to the subnet
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +This adds ip address 10.0.1.2/24 to ``eno2`` and a route to the subnet
```suggestion
Add ip address 10.0.1.2/24 to ``eno2`` and a route to the subnet
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +This sets ``port54`` up, adds ip address 10.0.3.2 and adds a route to the
```suggestion
Set ``port54`` up, add ip address 10.0.3.2 and add a route to the
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +This sets ``port54`` up, adds ip address 10.0.3.1 and adds a route to the
```suggestion
Set ``port54`` up, add ip address 10.0.3.1 and add a route to the
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +This sets ``port2`` up and adds the ip address 10.0.1.1/24.
```suggestion
Set ``port2`` up and add the ip address 10.0.1.1/24.
```

2021-09-07 18:49 UTC, jklare commented on network_configuration/static_routing.md
> +Here we will give a simple example of using static routes on four nodes. Two
```suggestion
Here we show a simple example of using static routes on four nodes. Two
```

2021-09-13 09:33 UTC, KanjiMonster requested changes

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +switches and two server, as shown on the figure below.
```suggestion
switches and two servers, as shown on the figure below.
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Set ``port2`` up and add the ip address 10.0.1.1/24.
```suggestion
Set ``port2`` up and add the IP address 10.0.1.1/24.
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Set ``port54`` up, add ip address 10.0.3.1 and add a route to the
```suggestion
Set ``port54`` up, add IP address 10.0.3.1 and add a route to the
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Set ``port2`` up and add ip address 10.0.2.1/24.
```suggestion
Set ``port2`` up and add IP address 10.0.2.1/24.
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Set ``port54`` up, add ip address 10.0.3.2 and add a route to the
```suggestion
Set ``port54`` up, add IP address 10.0.3.2 and add a route to the
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Add ip address 10.0.1.2/24 to ``eno2`` and a route to the subnet
```suggestion
Add IP address 10.0.1.2/24 to ``eno2`` and a route to the subnet
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Add ip address 10.0.2.2/24 to ``eno2`` and a route to the subnet
```suggestion
Add IP address 10.0.2.2/24 to ``eno2`` and a route to the subnet
```

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +Restart systemd-networkd or reboot the switches to apply network configuration.
What about the  servers?

2021-09-13 09:33 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +
It might be worthwhile to add some textual explanation here on assumptions, i.e. the servers are using systemd-networkd for network configuration as well, and the network interfaces connected to the switches is called eno2.

2021-09-13 11:36 UTC, hilmarm commented on network_configuration/static_routing.md
> +Restart systemd-networkd or reboot the switches to apply network configuration.
Completely true, forgot that the routes to 10.0.x.2/24 make no sense without the server config.

2021-09-13 13:31 UTC, hilmarm commented on network_configuration/static_routing.md
> +Restart systemd-networkd or reboot the switches to apply network configuration.
fixed

2021-09-13 13:31 UTC, hilmarm commented on network_configuration/static_routing.md
> +
Added a sentence explaining the figure

2021-09-13 14:29 UTC, KanjiMonster commented on network_configuration/static_routing.md
> +routes on two switches and two servers.
None of the other sections in this file use manual line breaks, so I don't think you should add them.

2021-09-14 14:56 UTC, KanjiMonster approved these changes

2021-09-14 14:56 UTC, merged