Added client_drivshell to list of ofdpa client tools
bisdn/bisdn.github.io pull request #118
Opened 2021-09-06 13:08 UTC by hilmarm

ofdpa should be mentioned at least in the list of ofdpa tools.
Added link to ofdpa-api where it says that BCM command is called.
Added output from client_drivshell help since documentation does not
exist.

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

2021-09-08 08:39 UTC, KanjiMonster requested changes

2021-09-08 08:39 UTC, KanjiMonster commented on tools/ofdpa_client_tools.md
> +client_drivhsell
alphabetical order plz

2021-09-08 08:39 UTC, KanjiMonster commented on tools/ofdpa_client_tools.md
> +``help`` flag produces the following output:
Cisco calls it the "Broadcom Shell" or "bcm-shell", while other sources call it "BCM Diag Shell", "BCM Diagnostic shell", so we should use similar terminology here.

That it does so via the OF-DPA API is an implementation detail that I don't think anyone cares about. The important part is that it issues the shell command, and prints its output.

I'm not sure if we need to state that it isn't publicly documented, this sentence feels weird and a bit defensive. 

I would just state that `client_drivshell help` will print a list of available commands, and `client_drivshell help <command>` will print the usage of a certain command. 

The list of available command changes with the switch model and SDK used, so I'm not sure if we need to reproduce it.

A warning that this diag shell accesses the internal switch state and modifying it may break proper operation of the switch until reboot might be good.

2021-09-08 14:30 UTC, hilmarm commented on tools/ofdpa_client_tools.md
> +``help`` flag produces the following output:
Thanks for the input, I agree with putting it like this.

2021-09-10 13:19 UTC, KanjiMonster requested changes

2021-09-10 13:19 UTC, KanjiMonster commented on tools/ofdpa_client_tools.md
> -
unrelated white space change?

2021-09-10 13:19 UTC, KanjiMonster commented on tools/ofdpa_client_tools.md
> +and prints the output. ``client_drivshell help`` will print a list of available
It does not execute the shell, it provides access to the shell, or sends commands to it. Also maybe drop the quotes around it, looks weird IMHO.

2021-09-10 13:35 UTC, hilmarm commented on tools/ofdpa_client_tools.md
> -
fixed

2021-09-10 13:36 UTC, hilmarm commented on tools/ofdpa_client_tools.md
> +and prints the output. ``client_drivshell help`` will print a list of available
Updated sentence and removed the quotation marks

2021-09-14 09:00 UTC, merged