Document management interface DHCP configuration file
bisdn/bisdn.github.io pull request #122
Opened 2021-09-22 14:33 UTC by rubensfig

Documents changed behaviour in bisdn/meta-switch#14.

Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>

2021-09-27 08:40 UTC, hilmarm reviewed
Just a suggestion

2021-09-27 08:40 UTC, hilmarm commented on getting_started/basic_networking.md
> +The BISDN Linux switches have a management interface, configured via `systemd-networkd`. By default, this file configures the interface to use DHCP, and can be opened as follows.
```suggestion
BISDN Linux uses `systemd-networks` to configure the management interface, which by default is set to use DHCP. You can edit the configuration file shown below to match your prefered setup. Please see the [systemd-networkd docs](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for more information.
```

2021-09-27 08:40 UTC, hilmarm commented on getting_started/basic_networking.md
> +root@bisdn-linux# cat /lib/systemd/network/80-wired.network
```suggestion
/lib/systemd/network/80-wired.network
```

2021-09-27 08:40 UTC, hilmarm commented on getting_started/basic_networking.md
> +root@bisdn-linux# cat /lib/systemd/network/80-wired.network
Also suggest to move to the `filename` above the code block, and then the contents inside the codeblock as we do in the bgp network configuration: https://github.com/bisdn/bisdn.github.io/edit/master/network_configuration/bgp.md line 72

2021-09-29 15:10 UTC, KanjiMonster commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networks` to configure the management interface, which by default is set to use DHCP. You can edit the configuration file shown below to match your prefered setup. Please se
```suggestion
BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. You can edit the configuration file shown below to match your prefered setup. Please see the [systemd-networkd docs](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for more information.
```

AFAIK Files in /lib aren't supposed to be edited by the user, you are supposed to create your own in /etc/systemd./network/

2021-09-29 15:13 UTC, KanjiMonster commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networks` to configure the management interface, which by default is set to use DHCP. You can edit the configuration file shown below to match your prefered setup. Please se
Especially since 80-wired.network is *not* marked as a configuration file, so it won't be backed up on update.

2021-09-30 08:11 UTC, jklare commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networks` to configure the management interface, which by default is set to use DHCP. You can edit the configuration file shown below to match your prefered setup. Please se
i agree with @KanjiMonster here, i think we should not encourage people to edit this file, but rather document that you can just add another file to /etc/systemd/network to overwrite this file (e.g. by choosing a lower number for the file name, so it will be read first and the 80-wired filed will be ignored)

2021-10-05 08:49 UTC, hilmarm commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. To overwrite the configuration of this file, add a custom file on the `/etc/systemd/net
```suggestion
BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. To overwrite the configuration of this file, add a custom file in the `/etc/systemd/network` directory, with a prefix number lower than `80`. Please see the [systemd-networkd docs](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for more information.
```

2021-10-05 08:49 UTC, hilmarm commented
Ready to merge after last comment addressed

2021-10-05 08:52 UTC, hilmarm approved these changes

2021-10-05 12:14 UTC, jklare requested changes

2021-10-05 12:14 UTC, jklare commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. To overwrite the configuration of this file, add a custom file in the `/etc/systemd/net
systemd-networkd is not by default set to use DHCP

2021-10-05 12:14 UTC, jklare commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. To overwrite the configuration of this file, add a custom file in the `/etc/systemd/net
please explain why lower than 80  and what "this file" is

2021-10-05 13:38 UTC, jklare commented on getting_started/basic_networking.md
> +BISDN Linux uses `systemd-networkd` to configure the management interface, which by default is set to use DHCP. To overwrite the configuration of this file, add a custom file in the `/etc/systemd/net
```suggestion
BISDN Linux uses `systemd-networkd` to configure the management interface. To allow users to ssh to and configure the switch without any further configuration after installing an image, our yocto build chain adds a default configuration file to `/lib/systemd/network/80-wired.network` (shown below), which configures all interfaces named "eth*" or "en*" to use DHCP. By using this configuration, the management interface of all switch platforms automatically uses DHCP for its own address configuration. To overwrite this configuration file, you can add a custom file in the `/etc/systemd/network` directory, with a prefix number lower than `80`. The lower prefix will make sure this file is read first when starting systemd-networkd (only the first `Match` for each interface is applied). Please see the [systemd-networkd docs](https://www.freedesktop.org/software/systemd/man/systemd.network.html) for more information.
```

2021-10-05 15:01 UTC, merged