Add accton-as4630-54pe related documentation
bisdn/bisdn.github.io pull request #133
Opened 2021-12-15 12:51 UTC by rubensfig

2021-12-15 13:36 UTC, KanjiMonster requested changes
info SFP LEDs being stuck on white is missing in known issues.

Also please follow the style of the document and add a Affected versions: line to all issues you add.

2021-12-15 13:36 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port.
After a few tests, there seem to be a general issue with fiber, regardless of autoneg or not.

2021-12-15 13:57 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port.
as a workaround, sticking

```
phy control 53-54 preemphasis=0x124106
```

Seems to make it link up with 40g and 100g with fiber on the 100g ports. The 25g ports seem to be unaffected.

2021-12-15 15:20 UTC, rubensfig commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port.
Should the workaround be built into the image?

2021-12-15 15:27 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port.
We already finalized the release images, unless we want to cancel the release no.

2021-12-15 15:38 UTC, hilmarm reviewed
Just some nitpickery

2021-12-15 15:38 UTC, hilmarm commented on limitations_and_known_issues.md
> +## Accton-AS4630-54pe: Link speed setting with interfaces cabled with fiber
```suggestion
## Accton-AS4630-54PE: Link speed setting with interfaces cabled with fiber
```

2021-12-15 15:38 UTC, hilmarm commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```suggestion
The Accton AS4630-54PE platform does not seem to autonegotiate consistently with the cabled fiber port. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```

2021-12-15 15:38 UTC, hilmarm commented on limitations_and_known_issues.md
> +## Accton-AS4630-54pe: LEDs for the SFP interfaces are stuck on white
```suggestion
## Accton-AS4630-54PE: LEDs for the SFP interfaces are stuck on white
```

2021-12-15 15:38 UTC, hilmarm commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform LEDs for the SFP interfaces maybe stuck on white.
```suggestion
The Accton AS4630-54PE platform LEDs for the SFP interfaces maybe stuck on white.
```

2021-12-15 15:38 UTC, hilmarm commented on limitations_and_known_issues.md
>  As documented in the currently open upstream FRR issue [#7299](https://github.com/FRRouting/frr/issues/7299), some routes may get dropped or are not correctly received when ports are flapping during
```suggestion
As documented in the currently open upstream FRR issue [#7299](https://github.com/FRRouting/frr/issues/7299), some routes may get dropped or are not correctly received when ports are flapping during EIGRP session establishment. For now, we recommend the workaround of restarting FRR after all ports are up if this behaviour is observed.
```

2021-12-15 15:40 UTC, KanjiMonster requested changes

2021-12-15 15:40 UTC, KanjiMonster commented on getting_started/install_onie.md
> +| Edgecore AS4630-54PE   | GRUB       |[v2020.08.00.03](https://support.edge-core.com/hc/en-us/articles/900004156326-AS4630-54PE-ONIE-v2020-08-00-03-latest)<sup>1</sup>|
```suggestion
| Edgecore AS4630-54PE   | GRUB       |[2020.08.00.03](https://support.edge-core.com/hc/en-us/articles/900004156326-AS4630-54PE-ONIE-v2020-08-00-03-latest)<sup>1</sup>|
```

2021-12-15 15:40 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform does not seem to autonegotiate consistently with the cabled fiber port. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
This still doesn't have to do anything with autonegotiation. 

The 100G ports currently do not properly link with link speeds other than 100G on fiber connections. Regardless if autoneg is enabled or not. And it only affects the 100G ports, the 25G port work fine in both 10G and 25G.

2021-12-15 15:40 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54pe platform LEDs for the SFP interfaces maybe stuck on white.
Unless something recently changed, they are always stuck on white.

2021-12-15 16:08 UTC, rubensfig commented on limitations_and_known_issues.md
>  As documented in the currently open upstream FRR issue [#7299](https://github.com/FRRouting/frr/issues/7299), some routes may get dropped or are not correctly received when ports are flapping during
Dropping as the change is not relevant for the PR.

2021-12-15 16:33 UTC, KanjiMonster requested changes

2021-12-15 16:33 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform LEDs for the SFP interfaces always stuck on white.
```suggestion
The Accton AS4630-54PE platform LEDs for the SFP interfaces are always stuck on white.
```

2021-12-15 16:33 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform does not seem to set the link speed consistently with the cabled fiber port. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```suggestion
The Accton AS4630-54PE platform may not properly establish a link when using a fiber connection on the 100G ports. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```

2021-12-16 09:48 UTC, jklare commented on limitations_and_known_issues.md
> +## Accton-AS4630-54PE: Link speed setting with interfaces cabled with fiber
```suggestion
## Accton-AS4630-54PE: Link speed setting for interfaces connected with optical modules
```

2021-12-16 09:48 UTC, jklare commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform may not properly establish a link when using a fiber connection on the 100G ports. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```suggestion
The Accton AS4630-54PE platform may not properly establish a link when using optical 100G modules. As a workaround, add the following configuration into `/etc/ofdpa/rc.soc`.
```

2021-12-16 09:48 UTC, jklare commented on limitations_and_known_issues.md
> +## Accton-AS4630-54PE: LEDs for the SFP interfaces are stuck on white
```suggestion
## Accton-AS4630-54PE: LEDs for the SFP interfaces signal in white colour
```

2021-12-16 09:48 UTC, jklare commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform LEDs for the SFP interfaces are always stuck on white.
```suggestion
The Accton AS4630-54PE platform LEDs for the SFP interfaces currently only use white colour for link and traffic signalling.
```

2021-12-16 09:52 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform LEDs for the SFP interfaces are always stuck on white.
No, they are lighting up white regardless of link or speed or if there is a module. All 6 LEDs currently are white in the testing setup, despite only 4 having a module inserted.

2021-12-16 09:52 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +The Accton AS4630-54PE platform LEDs for the SFP interfaces are always stuck on white.
Also IIRC they don't blink.

2021-12-16 11:22 UTC, KanjiMonster approved these changes

2021-12-16 11:31 UTC, KanjiMonster requested changes
I just found one more small thing, can you please add the platform to the list in `index.md`?

2021-12-16 16:58 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +Refer to https://github.com/bisdn/meta-open-network-linux/pull/24.
Since I cannot add suggestions with codeblocks, here the raw thingy:

The `poectl` utility uses a wrong path to access the poe controller device.

To work around this, edit `/usr/sbin/poectl` and change

```
systempath=/sys/kernel/debug/i2c-16-0020
```
to

```
systempath=/sys/kernel/debug/16-0020
```

2021-12-16 17:06 UTC, KanjiMonster approved these changes

2021-12-16 17:06 UTC, merged