add KNET documentation and known issues
bisdn/bisdn.github.io pull request #137
Opened 2022-03-14 15:05 UTC by KanjiMonster

Add some documentation on how to enable KNET interfaces and their known issues.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>

2022-03-14 15:15 UTC, jklare requested changes
lgtm, a couple of suggestions

2022-03-14 15:15 UTC, jklare commented on platform_configuration/bcm_knet_interfaces.md
> +nav_order: 3
```suggestion
nav_order: 6
```

2022-03-14 15:15 UTC, jklare commented on platform_configuration/bcm_knet_interfaces.md
> +Broadcom KNET network interfaces are an alternative implementation for the representation of the switch ports. They directly forward the packets in the kernel to and from the switch, reducing overhea
```suggestion
Broadcom KNET network interfaces ("bcm-knet") are an alternative for the "tun" interface type representation of the switch ports. They directly forward the packets in the kernel to and from the switch, reducing overhead and improving throughput and latency when communicating from the switch itself.
```

2022-03-14 15:15 UTC, jklare commented on platform_configuration/bcm_knet_interfaces.md
> +**Note**: Broadcom KNET network interfaces is still an experimental feature, and may not always work as expected.
```suggestion
**Note**: The use of Broadcom KNET network interfaces is still an experimental feature, and may not always work as expected. 
```

2022-03-15 09:12 UTC, KanjiMonster commented
Updated, and added a link to the known issues to encourage users to look there before reporting issues.

2022-03-15 10:56 UTC, jklare approved these changes
lgtm

2022-03-15 10:56 UTC, merged