Netlink buffer limitation update
bisdn/bisdn.github.io pull request #146
Opened 2022-05-13 06:38 UTC by hilmarm

The netlink buffer issue was fixed in the [v4.6.0 release](http://repo.bisdn.de.s3-eu-central-1.amazonaws.com/pub/onie/accton-as5835-54x/onie-bisdn-accton-as5835-54x-v4.6.0-releasenotes.txt)

So 4.5 is the last version with this issue.
Also removed some trailing spaces in a separate commit.

2022-05-25 08:37 UTC, KanjiMonster requested changes

2022-05-25 08:37 UTC, KanjiMonster commented on limitations_and_known_issues.md
> +Affected versions: 3.0 - 4.5
You need to move this from "Open issues" to "Resolved issues" as well.

2022-05-27 08:53 UTC, hilmarm commented on limitations_and_known_issues.md
> +Affected versions: 3.0 - 4.5
Good catch, moved to the resolved issues section

2022-05-30 09:54 UTC, KanjiMonster approved these changes

2022-05-30 09:54 UTC, merged