Update page on how to confgure baseboxd
bisdn/bisdn.github.io pull request #148
Opened 2022-05-19 14:49 UTC by hilmarm

Removed some old mentions of Fedora, updated section titles, and added some information on how to enable per-module logging.

We should first update the [default configuration file](https://github.com/bisdn/basebox/blob/master/pkg/systemd/sysconfig.template) in the basebox project.

2022-05-20 09:11 UTC, hilmarm commented
Wait for https://github.com/bisdn/basebox/pull/379 before merging this, as we might change the config file

2022-05-25 08:46 UTC, KanjiMonster requested changes

2022-05-25 08:46 UTC, KanjiMonster commented on getting_started/configure_baseboxd.md
> +### Configuration options and logging in baseboxd
Logging is also part of the configuration, so not sure we need to mention that separately. Also this makes it sound like it is something outside of the configuration.

2022-05-25 08:46 UTC, KanjiMonster commented on getting_started/configure_baseboxd.md
> +In order to apply changes in the baseboxd configuration, simply restart the baseboxd service:
The "simply" makes it sound a bit colloquial, not sure if I agree. Also it's never simple, we might want to suggest to reboot the switch instead or run this basebox change config script thingy to ensure that OF-DPA's configuration will be reset as well (when running on-switch).

2022-05-27 08:28 UTC, hilmarm commented on getting_started/configure_baseboxd.md
> +### Configuration options and logging in baseboxd
Updated section title to the more simple

> ### Configure baseboxd

2022-05-27 08:28 UTC, hilmarm commented on getting_started/configure_baseboxd.md
> +### baseboxd running configuration and logging
Updated the section title to say 'Configure'

2022-05-27 08:29 UTC, hilmarm commented on getting_started/configure_baseboxd.md
> +For example, if you want to set the log levels for the [https://github.com/bisdn/basebox/blob/master/src/netlink/cnetlink.h](cnetlink) and [https://github.com/bisdn/basebox/blob/master/src/netlink/nl
Good catch, I wanted the header files

2022-05-27 08:42 UTC, hilmarm commented on getting_started/configure_baseboxd.md
> +In order to apply changes in the baseboxd configuration, simply restart the baseboxd service:
Since the title says configure baseboxd I think it's safe to assume we are not changing OF-DPA config (although I might be wrong to assume it..)

I added both suggestions for applying the configuration, i.e. rebooting the switch OR restarting the service

2022-05-30 09:55 UTC, KanjiMonster approved these changes

2022-05-30 09:56 UTC, merged