vlan_bridging: clarify VLAN configuration on the bridge interface
bisdn/bisdn.github.io pull request #175
Opened 2023-02-23 15:20 UTC by KanjiMonster

The bridge interface does not need any VLANs configured for simple forwarding to work, so split out the bridge port VLAN configuration and treat it as optional.

Also fix the wrong claim that bridge ports inherit any VLAN configuration from the bridge, they only get assigned the default PVID if configured, if it is disabled, they will have no VLANs configured at all.

2023-02-24 09:06 UTC, hilmarm requested changes
Generally like the idea of splitting the configuration, and it's much neater this way.

2023-02-24 09:06 UTC, hilmarm commented on network_configuration/vlan_bridging.md
> +disabled. Since the ports which will be connected to the bridge have different
I am not sure I understand this sentence:

> Since the ports which will be connected to the bridge have different PVIDs, the default will be set to none. 

Do we mean:

> Since the ports in our example will have different PVIDs, we will set the  default bridge PVID to none.

2023-02-24 09:06 UTC, hilmarm commented on network_configuration/vlan_bridging.md
> +Finally, configuring the VLANs on the bridge member ports, and the bridge itself is done with the following commands.
```suggestion
Finally, configuring the VLANs on the bridge member ports is done with the following commands.
```

2023-02-24 09:06 UTC, hilmarm commented on network_configuration/vlan_bridging.md
> +Finally, configuring the VLANs on the bridge member ports, and the bridge itself is done with the following commands.
Since we dropped the commands below

2023-02-24 10:00 UTC, KanjiMonster commented on network_configuration/vlan_bridging.md
> +disabled. Since the ports which will be connected to the bridge have different
> I am not sure I understand this sentence:

This sentence was originally [written by you](https://github.com/bisdn/bisdn.github.io/commit/3b7791a7b4f1e#diff-2c56d737e499107764e693145cba4d15a6ed2d0ffe1295d0318fab302ae34996R42-R43), I just moved it around a bit ;P

I agree with the rewording though, and did that (slightly changed)

2023-02-24 10:00 UTC, KanjiMonster commented on network_configuration/vlan_bridging.md
> +Finally, configuring the VLANs on the bridge member ports, and the bridge itself is done with the following commands.
Done.

2023-02-24 14:38 UTC, KanjiMonster commented
Looks like the bridge needs to be in up state for learning to work, so a .network file is still needed, regardless whether it defines any VLANs or not.

2023-03-02 08:49 UTC, rubensfig approved these changes

2023-03-02 08:49 UTC, merged