platform: document default installation files
bisdn/bisdn.github.io pull request #188
Opened 2024-06-07 10:11 UTC by rubensfig

Document bisdn/meta-switch/pull/203 functionality to provide default installation of l2 functionality.

2024-06-14 08:32 UTC, ideaship commented on platform_configuration/default_installer.md
> +BISDN_DEFAULT_CONFIG="simple-l2-bridge" onie-nos-install http://repo.bisdn.de.s3-eu-central-1.amazonaws.com/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin
You can shorten the hostname to repo.bisdn.de.
Also, given that 5.1.1 does not have this functionality, maybe replace v5.1.1 with [...] or something.

2024-06-14 08:32 UTC, ideaship commented on platform_configuration/default_installer.md
> +**WARNING** This page provides a tool to provide default configuration in your switch. Only run this command if you are prepared to lose your configuration!
```suggestion
**WARNING** This page documents a mechanism for reinstalling your switch with a default configuration. Only run this command if you are prepared to lose all files in your current BISDN Linux installation.
```
Just a suggestion, but we to make clear that the user is not only losing /etc/systemd/network or other configuration files, but _all_ files. The mechanism ignores system-backup.txt and user-backup.txt. It is more like onie-bisdn-uninstall than onie-bisdn-upgrade.

2024-06-18 09:48 UTC, KanjiMonster requested changes
I think it would make more sense to put this into https://github.com/bisdn/bisdn.github.io/blob/main/getting_started/install_bisdn_linux.md instead of a separate page, since you might want to know about this before doing an installation.

2024-06-18 09:48 UTC, KanjiMonster commented on platform_configuration/default_installer.md
> +The `baseboxd` package includes default systemd-networkd configuration files. These files initialize bisdn-linux to provide a default l2 switch forwarding functionality. To configure this, pass the `
That these configuration files come from the baseboxd package is an implementation detail that really doesn't matter for users.

I think this paragraph currently could improve the explanation for why a user would want to use it. E.g. something like

```suggestion
BISDN Linux by default provides no network configuration for the switch ports. To allow a more switch like default configuration, it is possible to use the environment variable `BISDN_DEFAULT_CONFIG` while installing BISDN Linux to provide a default network configuration.
```

2024-06-18 09:48 UTC, KanjiMonster commented on platform_configuration/default_installer.md
> +**WARNING** This page documents a mechanism for reinstalling your switch with a default configuration. Only run this command if you are prepared to lose all files in your current BISDN Linux installa
The wording is a bit redundant, no need to reference that this is a page.

```suggestion
**WARNING** Setting a default configuration will reset the file system to the initial state. Only use this if you are prepared to lose all modifications of your current BISDN Linux installation.
```

2024-06-19 09:12 UTC, rubensfig reviewed
Addressed all comments

2024-06-28 09:31 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +The `baseboxd` supported files are in the file system under the `/usr/share/baseboxd/default_configurations/` path.
I don't think this helps and just confuses (from a user perspective what has this to do with baseboxd? how would you access this path?).

What would be nice to have a table here with all supported values and an explanation of it.

* (empty) => just takes over the previous installation's configuration, if there is one (default)
* simple-l2-bridge => removes existing configuration, puts all ports into a bridge, behaves like an unmanaged switch
* none => removes existing configuration, resetting the installation to the default state with no configuration on switch ports

2024-07-09 08:06 UTC, KanjiMonster requested changes

2024-07-09 08:06 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +|simple-l2-bridge|Removes existing configuration and initializes the switch to behave as an unmanaged switch||
1. Lets align the table in the source as well, to make it more readable on the command line.
2. Lets be more explicit in explaining the network configuration options.

```suggestion
|`BISDN_DEFAULT_CONFIG` Value|Outcome                                                                                        |Default|
|(Empty)                     |Use previous installation configuration                                                        |Y      |
|`none`                      |Removes existing configuration and initializes the switch with all ports disabled              |       |
|`simple-l2-bridge`          |Removes existing configuration and initializes the switch to forward traffic between all ports |       |
```

2024-07-09 09:16 UTC, KanjiMonster approved these changes
LGTM

2024-07-18 08:48 UTC, merged