Add xSTP documentation
bisdn/bisdn.github.io pull request #68
Opened 2020-08-18 14:29 UTC by rubensfig

2020-08-20 13:11 UTC, rr-santos requested changes

2020-08-20 13:11 UTC, rr-santos commented on network_configuration/stp.md
> +There is currently no RSTP support in the Linux Kernel and therefore BISDN Linux uses [mstpd](https://github.com/mstpd/mstpd) to configure and manage RSTP.
Is how to enable mstpd in BSDN linux documented somewhere else already? If not, it should be added here that mstpd  is not enabled by default and how to enable/start it.

2020-08-20 13:11 UTC, rr-santos commented on network_configuration/stp.md
> +mstpd takes over the stp_state flag and instead of setting it to 1 (referring to the Kernel implementation), it will be set to 2 (referring to the Userspace implementation of STP, in this case handle
This sentence is a bit confusing. We don't need to set the stp_state flag when creating a bridge and mstpd will do that automatically by enabling stp when we create a bridge?

2020-08-20 13:11 UTC, rr-santos commented on network_configuration/stp.md
> +After setting up the bridge and bridge ports, the RSTP state on the bridge can be managed over the `mstpdctl` utility. The following command shows example output of commands.
```suggestion
After setting up the bridge and bridge ports, the RSTP state on the bridge can be managed over the `mstpdctl` utility. The following command shows an example command output.
```

2020-08-20 13:11 UTC, rr-santos commented on network_configuration/stp.md
> +15: port2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br0 state forwarding priority 32 cost 2
either br0 or swbridge

2020-08-20 13:11 UTC, rr-santos commented on network_configuration/stp.md
> +After setting up the bridge and bridge ports, the STP state on the bridge can be managed over the `brctl` utility. The following command shows example output of a command.
```suggestion
After setting up the bridge and bridge ports, the STP state on the bridge can be managed over the `brctl` utility. The following example shows the output of a `brctl` command:
```

2020-08-20 14:40 UTC, rr-santos requested changes
See pending suggestions, other than that LGTM

2020-08-20 14:40 UTC, rr-santos commented on network_configuration/stp.md
> +The same topology as above is considered in this scenario.
```suggestion
When `mstpd` is enabled, any configured bridge will have STP enabled by default. Therefore, it is not required to specify the `stp_state` flag when creating a bridge:
```

2020-08-20 14:40 UTC, rr-santos commented on network_configuration/stp.md
> +The stp_state flag has three possible values: 0, 1, 2. By choosing 1 then the Kernel implementation of STP will be used, and when choosing 2 then there is a Userspace implementation of STP. Enabling
```suggestion

```

2020-08-20 14:40 UTC, rr-santos commented on network_configuration/stp.md
> +
```suggestion

**WARNING**: The `brctl` tool does not work with bridges managed by `mstpd`.
{: .label .label-yellow }

```

2020-08-20 14:49 UTC, rr-santos approved these changes
LGTM

2020-08-26 14:52 UTC, hilmarm commented on network_configuration/stp.md
> +title: Spanning Tree (xSTP)
already fixed

2020-08-26 14:52 UTC, hilmarm commented on network_configuration/stp.md
> +# Spanning Tree (xSTP)
fixed

2020-08-26 14:54 UTC, hilmarm commented on network_configuration/stp.md
> +15: port2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br0 state forwarding priority 32 cost 2
has been changed to swbridge

2020-08-26 14:54 UTC, hilmarm commented on network_configuration/stp.md
> +mstpd takes over the stp_state flag and instead of setting it to 1 (referring to the Kernel implementation), it will be set to 2 (referring to the Userspace implementation of STP, in this case handle
Sentence has been rewritten

2020-08-27 09:25 UTC, closed without merging