add user-backup doc
bisdn/bisdn.github.io pull request #75
Opened 2020-09-11 12:26 UTC by rubensfig

2020-09-11 12:34 UTC, KanjiMonster requested changes

2020-09-11 12:34 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +- comments, like this block, prefixed with #.
This block isn't prefixed with # ;p

2020-09-11 12:34 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +To backup files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file.
You might want to point out by default it already backs up configuration, so you only need this for custom files. So users won't think they need to add their network configuration etc here to keep it preserved.

2020-09-14 07:12 UTC, hilmarm commented on getting_started/install_bisdn_linux.md
> +To backup files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file. BISDN Linux keeps by default the following files/ directories:
I would move this sentence around to 'By default BIS...'(my prefered suggestion) or 'BISDN .... directories by default'

2020-09-14 08:31 UTC, hilmarm commented
Should we also note that this is only valid when you go FROM v3.4.0 and onwards, and not just when you update to v3.4.0?

2020-09-14 08:38 UTC, KanjiMonster commented
> Should we also note that this is only valid when you go FROM v3.4.0 and onwards, and not just when you update to v3.4.0?

If you manually create the file, it will already be used when updating to v3.4.0 from a previous version.

2020-09-14 08:44 UTC, hilmarm commented
ok great, then there should not be any issue.

2020-09-14 08:51 UTC, rubensfig commented on getting_started/install_bisdn_linux.md
> +To backup files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file. BISDN Linux keeps by default the following files/ directories:
```suggestion
To backup files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file. By default BISDN Linux keeps the following files/ directories:
```

2020-09-14 09:25 UTC, hilmarm commented
lgtm

2020-09-14 10:39 UTC, KanjiMonster requested changes

2020-09-14 10:39 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +/etc/ofdpa-grpc.conf
That's only the files not caught by opkg's conffiles, which also triggers the backup of the following files:

```
/etc/ca-certificates.conf
/etc/dbus-1/session.conf
/etc/dbus-1/system.conf
/etc/default/ofagent
/etc/default/ofdpa
/etc/default/ryu-manager
/etc/frr/babeld.conf
/etc/frr/bfdd.conf
/etc/frr/bgpd.conf
/etc/frr/eigrpd.conf
/etc/frr/isisd.conf
/etc/frr/ldpd.conf
/etc/frr/nhrpd.conf
/etc/frr/ospf6d.conf
/etc/frr/ospfd.conf
/etc/frr/pbrd.conf
/etc/frr/pimd.conf
/etc/frr/ripd.conf
/etc/frr/ripngd.conf
/etc/frr/sharpd.conf
/etc/frr/staticd.conf
/etc/frr/vtysh.conf
/etc/fstab
/etc/hostname
/etc/hosts
/etc/inputrc
/etc/machine-id
/etc/motd
/etc/nsswitch.conf
/etc/ofdpa/rc.soc
/etc/profile
/etc/redis/redis.conf
/etc/shells
/etc/ssh/ssh_config
/etc/ssh/sshd_config
/etc/ssl/openssl.cnf
/etc/sudoers
/etc/sysctl.conf
/etc/systemd/coredump.conf
/etc/systemd/journald.conf
/etc/systemd/logind.conf
/etc/systemd/system.conf
/etc/systemd/user.conf
```

But maybe instead of explicitly mentioning each and every file (and needing to update it everytime we change that), just point to the sources of the information? Something like

```
By default BISDN Linux keeps files/directories based on packages' configuration file lists (located at `/var/lib/opkg/info/*.conffiles`) and the list in `/etc/default/system-backup.txt`.

To backup additional files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file.
```

2020-09-14 10:39 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +To backup files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file. By default BISDN Linux keeps the following files/ directories:
I would move the first sentence to after the information what is backed up by default. And then probably something like

> To backup additional files when installing a new BISDN Linux version, ...

2020-09-15 08:48 UTC, hilmarm commented
@KanjiMonster Have your comments been addressed?

2020-09-15 08:53 UTC, KanjiMonster requested changes

2020-09-15 08:53 UTC, KanjiMonster commented on getting_started/install_bisdn_linux.md
> +By default BISDN Linux keeps files/directories based on packages' configuration file lists (located at `/var/lib/opkg/info/*.conffiles`) and the list in `/etc/default/system-backup.txt`. This `user-b
Now you removed too much, as a user I wouldn't know what `user-backup.txt` you are talking about (I might be able to guess).
```suggestion
By default BISDN Linux keeps files/directories based on packages' configuration file lists (located at `/var/lib/opkg/info/*.conffiles`) and the list in `/etc/default/system-backup.txt`.

To backup files additional files when installing a new BISDN Linux version, use the `/etc/default/user-backup.txt` file. This `user-backup.txt` file supports a simple syntax to configure a custom list of files to keep during system upgrade:
```

2020-09-16 09:21 UTC, KanjiMonster approved these changes
LGTM

2020-09-16 09:24 UTC, merged